apiVersion: v1
kind: Service
metadata:
  name: rails-app-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001  # Optional: specify a custom nodePort
  selector:
    app: rails-app
